"""empty message

Revision ID: 5e9a1abb5b7b
Revises: baf21e6b87a3
Create Date: 2018-02-01 16:51:51.275871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9a1abb5b7b'
down_revision = 'baf21e6b87a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.String(length=32), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('previous_report_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['previous_report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=512), nullable=True),
    sa.Column('address1', sa.String(length=1024), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('zipcode', sa.String(length=128), nullable=True),
    sa.Column('client_start_date', sa.DateTime(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('bu_division', sa.String(length=64), nullable=True),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('sub', sa.String(length=128), nullable=True),
    sa.Column('bu_relationship_managers', sa.String(length=128), nullable=True),
    sa.Column('coo', sa.String(length=128), nullable=True),
    sa.Column('ss_top_50', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('core_ops_auditlocation', sa.String(length=128), nullable=True),
    sa.Column('pna_team_lead_site_lead', sa.String(length=128), nullable=True),
    sa.Column('pna_lead', sa.String(length=128), nullable=True),
    sa.Column('pna_last_visit', sa.DateTime(), nullable=True),
    sa.Column('senior_contact_name', sa.String(length=1024), nullable=True),
    sa.Column('senior_contact_email', sa.String(length=1024), nullable=True),
    sa.Column('senior_contact_tel', sa.String(length=128), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=1024), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=1024), nullable=True),
    sa.Column('primary_contact_tel', sa.String(length=128), nullable=True),
    sa.Column('isa_portal', sa.String(length=128), nullable=True),
    sa.Column('pna_whatchlist', sa.String(length=128), nullable=True),
    sa.Column('since', sa.DateTime(), nullable=True),
    sa.Column('late_deliverables_qtr', sa.Float(), nullable=True),
    sa.Column('error_memos_qstrs', sa.Float(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_dev_opp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_name', sa.String(length=128), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('projected_revenue', sa.Float(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('survey_history', sa.Text(), nullable=True),
    sa.Column('client_comments', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('opportunity', sa.Text(), nullable=True),
    sa.Column('threats', sa.String(length=128), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_engagement', sa.String(length=128), nullable=True),
    sa.Column('executive_engagement_last_visit', sa.DateTime(), nullable=True),
    sa.Column('cab', sa.String(length=128), nullable=True),
    sa.Column('client_service', sa.String(length=128), nullable=True),
    sa.Column('client_service_last_visit', sa.DateTime(), nullable=True),
    sa.Column('client_service_next_visit', sa.DateTime(), nullable=True),
    sa.Column('solutions', sa.String(length=128), nullable=True),
    sa.Column('solutions_last_visit', sa.DateTime(), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.Column('discussion_next_visit', sa.DateTime(), nullable=True),
    sa.Column('future_engagement_plan', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_size', sa.Float(), nullable=True),
    sa.Column('total_pna_revenue', sa.Float(), nullable=True),
    sa.Column('direct_revenue', sa.Float(), nullable=True),
    sa.Column('indirect_revenue', sa.Float(), nullable=True),
    sa.Column('margin_revenue', sa.Float(), nullable=True),
    sa.Column('total_ss_revenue', sa.Float(), nullable=True),
    sa.Column('market_data_fees', sa.Float(), nullable=True),
    sa.Column('market_data_billed', sa.Float(), nullable=True),
    sa.Column('contract_ex', sa.String(length=64), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('client_score', sa.Float(), nullable=True),
    sa.Column('bu_score', sa.Float(), nullable=True),
    sa.Column('pna_score', sa.Float(), nullable=True),
    sa.Column('client_sentiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_sentiment_id'], ['client_sentiment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ss', sa.Boolean(), nullable=True),
    sa.Column('third_party', sa.Boolean(), nullable=True),
    sa.Column('revenue_strategy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_strategy_id'], ['revenue_strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_detail')
    op.drop_table('question_score')
    op.drop_table('revenue_strategy')
    op.drop_table('engagement_strategy')
    op.drop_table('client_sentiment')
    op.drop_table('business_dev_opp')
    op.drop_table('basic_info')
    op.drop_table('report')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('service')
    op.drop_table('group')
    # ### end Alembic commands ###
