"""empty message

Revision ID: baf21e6b87a3
Revises: 
Create Date: 2018-01-31 18:14:35.267170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf21e6b87a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('finance_pnl_code', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('bu_division', sa.String(length=128), nullable=True),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('team_lead', sa.String(length=128), nullable=True),
    sa.Column('manager', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=128), nullable=True),
    sa.Column('cs_name_sign_off', sa.String(length=128), nullable=True),
    sa.Column('sign_off_date', sa.String(length=128), nullable=True),
    sa.Column('plan_market_value', sa.Float(), nullable=True),
    sa.Column('total_value_of_service', sa.Float(), nullable=True),
    sa.Column('billed', sa.Float(), nullable=True),
    sa.Column('unbilled', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_address_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=1024), nullable=True),
    sa.Column('contact_name', sa.String(length=1024), nullable=True),
    sa.Column('contact_hierarchy', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('telephone', sa.String(length=128), nullable=True),
    sa.Column('address1', sa.Text(), nullable=True),
    sa.Column('address2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=512), nullable=True),
    sa.Column('zipcode', sa.String(length=128), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('salesforceid', sa.String(length=128), nullable=True),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('mktsubsegment', sa.String(length=128), nullable=True),
    sa.Column('insurance', sa.String(length=128), nullable=True),
    sa.Column('bu_division', sa.String(length=128), nullable=True),
    sa.Column('businessunithead', sa.String(length=128), nullable=True),
    sa.Column('oracleid', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('iis_top_100', sa.String(length=128), nullable=True),
    sa.Column('ssia_top_tier', sa.String(length=128), nullable=True),
    sa.Column('directpublish', sa.String(length=128), nullable=True),
    sa.Column('clientstartdate', sa.String(length=128), nullable=True),
    sa.Column('dateclientterminated', sa.String(length=128), nullable=True),
    sa.Column('site_lead', sa.String(length=128), nullable=True),
    sa.Column('team_lead', sa.String(length=128), nullable=True),
    sa.Column('manager', sa.String(length=128), nullable=True),
    sa.Column('primary_client_contact', sa.String(length=128), nullable=True),
    sa.Column('analyst_1', sa.String(length=128), nullable=True),
    sa.Column('analyst_2', sa.String(length=128), nullable=True),
    sa.Column('analyst_3', sa.String(length=128), nullable=True),
    sa.Column('site', sa.String(length=128), nullable=True),
    sa.Column('bu_relationship_managers', sa.String(length=128), nullable=True),
    sa.Column('bu_client_service', sa.String(length=128), nullable=True),
    sa.Column('compliance_cs', sa.String(length=128), nullable=True),
    sa.Column('auditlocation', sa.String(length=128), nullable=True),
    sa.Column('acctcontact', sa.String(length=128), nullable=True),
    sa.Column('pnasrvr', sa.String(length=128), nullable=True),
    sa.Column('mchregion', sa.String(length=128), nullable=True),
    sa.Column('daily', sa.String(length=128), nullable=True),
    sa.Column('sector_name', sa.String(length=128), nullable=True),
    sa.Column('oversight_site', sa.String(length=128), nullable=True),
    sa.Column('oversight_group', sa.String(length=128), nullable=True),
    sa.Column('operations_email_dist', sa.String(length=128), nullable=True),
    sa.Column('jv_email_dist', sa.String(length=128), nullable=True),
    sa.Column('client_specific_email_dist', sa.String(length=128), nullable=True),
    sa.Column('watchlist', sa.String(length=128), nullable=True),
    sa.Column('cm_requires_2nd_approver', sa.String(length=128), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_name', sa.String(length=512), nullable=True),
    sa.Column('question_column_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salesforce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('opportunity_id', sa.String(length=128), nullable=True),
    sa.Column('created_date', sa.String(length=128), nullable=True),
    sa.Column('account_name', sa.String(length=128), nullable=True),
    sa.Column('opportunity_name', sa.String(length=128), nullable=True),
    sa.Column('probability', sa.String(length=128), nullable=True),
    sa.Column('projected_annualized_revenue_currency', sa.String(length=128), nullable=True),
    sa.Column('projected_annualized_revenue', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('business_unit', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('executive_synopsis', sa.Text(), nullable=True),
    sa.Column('product_family', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('rollup_business_unit', sa.String(length=128), nullable=True),
    sa.Column('rollup_team_lead', sa.String(length=128), nullable=True),
    sa.Column('primary_incumbent', sa.String(length=128), nullable=True),
    sa.Column('decision_date', sa.String(length=128), nullable=True),
    sa.Column('last_modified_date', sa.String(length=128), nullable=True),
    sa.Column('last_modified_by', sa.String(length=128), nullable=True),
    sa.Column('rollup_last_comment', sa.Text(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.String(length=128), nullable=True),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_hierarchy', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('telephone', sa.String(length=128), nullable=True),
    sa.Column('address1', sa.String(length=128), nullable=True),
    sa.Column('address2', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('zipcode', sa.String(length=128), nullable=True),
    sa.Column('client_response_received', sa.String(length=128), nullable=True),
    sa.Column('q1', sa.Float(), nullable=True),
    sa.Column('q2', sa.Float(), nullable=True),
    sa.Column('q3', sa.Float(), nullable=True),
    sa.Column('q4', sa.Float(), nullable=True),
    sa.Column('q5', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('score', sa.String(length=128), nullable=True),
    sa.Column('bu_rm', sa.String(length=128), nullable=True),
    sa.Column('bu_rm_email', sa.String(length=128), nullable=True),
    sa.Column('rm1', sa.String(length=128), nullable=True),
    sa.Column('rm2', sa.String(length=128), nullable=True),
    sa.Column('rm3', sa.String(length=128), nullable=True),
    sa.Column('rm4', sa.String(length=128), nullable=True),
    sa.Column('rm5', sa.String(length=128), nullable=True),
    sa.Column('bu_cs_lead', sa.String(length=128), nullable=True),
    sa.Column('bu_cs_lead_email', sa.String(length=128), nullable=True),
    sa.Column('cs1', sa.String(length=128), nullable=True),
    sa.Column('cs2', sa.String(length=128), nullable=True),
    sa.Column('cs3', sa.String(length=128), nullable=True),
    sa.Column('cs4', sa.String(length=128), nullable=True),
    sa.Column('cs5', sa.String(length=128), nullable=True),
    sa.Column('c_performance_lead', sa.String(length=128), nullable=True),
    sa.Column('performance_lead_email', sa.String(length=128), nullable=True),
    sa.Column('p1', sa.String(length=128), nullable=True),
    sa.Column('p2', sa.String(length=128), nullable=True),
    sa.Column('p3', sa.String(length=128), nullable=True),
    sa.Column('p4', sa.String(length=128), nullable=True),
    sa.Column('p5', sa.String(length=128), nullable=True),
    sa.Column('p_performance_lead', sa.String(length=128), nullable=True),
    sa.Column('team_lead', sa.String(length=128), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    op.drop_table('salesforce')
    op.drop_table('question')
    op.drop_table('client_master')
    op.drop_table('client_address_book')
    op.drop_table('billing')
    # ### end Alembic commands ###
